galaxy_info:
  author: "GSA and ISE"
  description: "Ansible role to apply Windows Server 2016 GSA Baseline"
  company: GSA
  license: MIT
  min_ansible_version: 2.4

  platforms:
  - name: WIN
    versions:
      - 2016

dependencies: []
